# Configuração do Servidor Spring
server.port=8080

# Configuração do PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/logitrack_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
# Usamos 'validate' para garantir que as entidades mapeadas no Java batem com o banco sem alterar as tabelas já criadas pelo script
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase Auth project configuration (public URL and publishable key)
supabase.url=${SUPABASE_URL:}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY:}
